apiVersion: apps/v1
kind: Deployment
metadata:
  name: lbgcalc
  labels:
    app: lbgcalc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lbgcalc
      
  template:
    metadata:
      labels:
        app: lbgcalc
        tier: lbgcalc
    spec:
      # automountServiceAccountToken: false
      containers:
        - name: lbgcalc
          image: agray998/vatcalc:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "8Mi"
              cpu: "50m"
              ephemeral-storage: "2Gi"
            limits:
              memory: "16Mi"
              cpu: "100m"
              ephemeral-storage: "4Gi"
          ports:
          - containerPort: 80
            name: lbgcalc
